[workspace]
members = ["./flipt-engine-ffi", "./flipt-client-browser", "./flipt-evaluation"]
resolver = "2"

[profile.release]
strip = true
rpath = true

[profile.release.package.flipt-engine-wasm]
opt-level = "s"
